name: HelpCmdPE
main: Vaivez66\HelpCmdPE\HelpCmd
version: 1.0.0
api: [1.12.0, 2.0.0]
load: POSTWORLD
authors: [Vaivez66]
description: "Customize your help command!"
permissions:
  help.cmd.pe:
    description: 'Permission to perform /help with customization'
    default: true